GET 127.0.0.1:8080/recipes/1
###
POST 127.0.0.1:8080/recipes/create/ingredient
Content-Type: application/json

{
      "name": "творог",
      "weight": 350,
      "unit": "г"
    }




###
POST 127.0.0.1:8080/recipes/create
Content-Type: application/json

{
  "name": "Сырники из творога",
  "cookingTime": 30,
  "ingredients": [{
    "name": "твороггг",
    "weight": 350,
    "unit": "г"
  }],
  "manual": [
    "test",
    "test"
  ]
}
